# Generated by Django 4.2.7 on 2026-01-15 07:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='recipe',
            name='category',
            field=models.CharField(choices=[('Супы', 'Супы'), ('Основные блюда', 'Основные блюда'), ('Салаты', 'Салаты'), ('Десерты', 'Десерты'), ('Завтраки', 'Завтраки'), ('Напитки', 'Напитки'), ('Выпечка', 'Выпечка')], default='Основные блюда', max_length=50, verbose_name='Категория'),
        ),
    ]
